export { default as ErrorPage } from './ErrorPage';
export { default as MainPage } from './MainPage';
export { default as ProfilePage } from './ProfilePage';
export { default as RegisterPage } from './RegisterPage';
export { default as RootPage } from './RootPage';
export { default as SearchMapPage } from './SearchMapPage';
export { default as UserInfoPage } from './UserInfoPage';
export { default as StoreDetailPage } from './UserInfoPage';
export { default as SigninPage } from './SigninPage';
